/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export { ApiError } from './core/ApiError';
export { CancelablePromise, CancelError } from './core/CancelablePromise';
export { OpenAPI } from './core/OpenAPI';
export type { OpenAPIConfig } from './core/OpenAPI';

export type { AlterarCompraDTO } from './models/AlterarCompraDTO';
export type { AlterarCompraItemDTO } from './models/AlterarCompraItemDTO';
export type { AlterarCompraItemParcialDTO } from './models/AlterarCompraItemParcialDTO';
export type { AlterarCompraItemResultadoDTO } from './models/AlterarCompraItemResultadoDTO';
export type { AlterarCompraParcialDTO } from './models/AlterarCompraParcialDTO';
export type { AlterarContratoDTO } from './models/AlterarContratoDTO';
export type { AlterarParcialAmparoLegalDTO } from './models/AlterarParcialAmparoLegalDTO';
export type { AlterarParcialCatalogoDTO } from './models/AlterarParcialCatalogoDTO';
export type { AlterarParcialDominioGenericoDTO } from './models/AlterarParcialDominioGenericoDTO';
export type { AlterarParcialPermissaoUsuarioDTO } from './models/AlterarParcialPermissaoUsuarioDTO';
export type { AlterarParcialTipoInstrumentoConbrancaDTO } from './models/AlterarParcialTipoInstrumentoConbrancaDTO';
export type { AlterarParcialTipoInstrumentoConvocatorioDTO } from './models/AlterarParcialTipoInstrumentoConvocatorioDTO';
export type { AlterarTermoContratoDTO } from './models/AlterarTermoContratoDTO';
export type { AlterarUnidadeOrgaoDTO } from './models/AlterarUnidadeOrgaoDTO';
export type { AlterarUsuarioDTO } from './models/AlterarUsuarioDTO';
export type { AmparoLegal } from './models/AmparoLegal';
export type { AmparoLegalDTO } from './models/AmparoLegalDTO';
export type { AmparoLegalModalidadeInstrumentoConvocatorioCommand } from './models/AmparoLegalModalidadeInstrumentoConvocatorioCommand';
export type { AtaRegistroPreco } from './models/AtaRegistroPreco';
export type { AtaRegistroPrecoAlteracaoDTO } from './models/AtaRegistroPrecoAlteracaoDTO';
export type { AtaRegistroPrecoDTO } from './models/AtaRegistroPrecoDTO';
export type { AtaRegistroPrecoInclusaoDTO } from './models/AtaRegistroPrecoInclusaoDTO';
export type { CamposLoginDTO } from './models/CamposLoginDTO';
export type { CatalogoDTO } from './models/CatalogoDTO';
export type { Categoria } from './models/Categoria';
export type { Compra } from './models/Compra';
export type { ConsultarAmparoLegalModalidadeInstrumentoConvocatorioDTO } from './models/ConsultarAmparoLegalModalidadeInstrumentoConvocatorioDTO';
export type { ConsultarInstrumentoCobrancaDTO } from './models/ConsultarInstrumentoCobrancaDTO';
export type { ConsultarModalidadeCriterioJulgamentoDTO } from './models/ConsultarModalidadeCriterioJulgamentoDTO';
export type { ConsultarModalidadeFonteOrcamentariaDTO } from './models/ConsultarModalidadeFonteOrcamentariaDTO';
export type { ContratacaoFonteOrcamentariaDTO } from './models/ContratacaoFonteOrcamentariaDTO';
export type { CredenciaisDTO } from './models/CredenciaisDTO';
export type { DominioGenericoDTO } from './models/DominioGenericoDTO';
export type { DominioGenericoMinimoDTO } from './models/DominioGenericoMinimoDTO';
export type { DominioGenericoResumidoDTO } from './models/DominioGenericoResumidoDTO';
export type { EnteCredenciaisDTO } from './models/EnteCredenciaisDTO';
export type { EventoNotaFiscalConsultaDTO } from './models/EventoNotaFiscalConsultaDTO';
export type { ExcluirContratacaoFonteOrcamentariaDTO } from './models/ExcluirContratacaoFonteOrcamentariaDTO';
export type { ExcluirDominioGenericoDTO } from './models/ExcluirDominioGenericoDTO';
export type { ExcluirInstrumentoCobrancaContratoDTO } from './models/ExcluirInstrumentoCobrancaContratoDTO';
export type { ExclusaoDTO } from './models/ExclusaoDTO';
export type { ExclusaoItemPcaDTO } from './models/ExclusaoItemPcaDTO';
export type { ExclusaoListaItensPcaDTO } from './models/ExclusaoListaItensPcaDTO';
export type { IErroValidacaoDTO } from './models/IErroValidacaoDTO';
export type { IncluirAmparoLegalDTO } from './models/IncluirAmparoLegalDTO';
export type { IncluirCatalogoDTO } from './models/IncluirCatalogoDTO';
export type { IncluirCompraItemDTO } from './models/IncluirCompraItemDTO';
export type { IncluirCompraItemResultadoDTO } from './models/IncluirCompraItemResultadoDTO';
export type { IncluirContratacaoFonteOrcamentariaDTO } from './models/IncluirContratacaoFonteOrcamentariaDTO';
export type { IncluirContratoDTO } from './models/IncluirContratoDTO';
export type { IncluirDominioGenericoDTO } from './models/IncluirDominioGenericoDTO';
export type { IncluirInstrumentoCobrancaContratoDTO } from './models/IncluirInstrumentoCobrancaContratoDTO';
export type { IncluirOrgaoDTO } from './models/IncluirOrgaoDTO';
export type { IncluirPlanoContratacaoDTO } from './models/IncluirPlanoContratacaoDTO';
export type { IncluirPlanoContratacaoItemDTO } from './models/IncluirPlanoContratacaoItemDTO';
export type { IncluirTermoContratoDTO } from './models/IncluirTermoContratoDTO';
export type { IncluirTipoInstrumentoCobrancaDTO } from './models/IncluirTipoInstrumentoCobrancaDTO';
export type { IncluirTipoInstrumentoConvocatorioDTO } from './models/IncluirTipoInstrumentoConvocatorioDTO';
export type { IncluirTipoInstrumentoConvocatorioModoDisputaDTO } from './models/IncluirTipoInstrumentoConvocatorioModoDisputaDTO';
export type { IncluirUnidadeOrgaoDTO } from './models/IncluirUnidadeOrgaoDTO';
export type { IncluirUsuarioOrgaoDTO } from './models/IncluirUsuarioOrgaoDTO';
export type { InserirUsuarioDTO } from './models/InserirUsuarioDTO';
export type { IRecuperarPlanoItemDTO } from './models/IRecuperarPlanoItemDTO';
export type { ItemNotaFiscalConsultaDTO } from './models/ItemNotaFiscalConsultaDTO';
export type { Modalidade } from './models/Modalidade';
export type { ModalidadeCriterioJulgamentoDTO } from './models/ModalidadeCriterioJulgamentoDTO';
export type { ModalidadeFonteOrcamentariaDTO } from './models/ModalidadeFonteOrcamentariaDTO';
export type { ModoDisputa } from './models/ModoDisputa';
export type { MoedaResumidoDTO } from './models/MoedaResumidoDTO';
export type { Municipio } from './models/Municipio';
export type { NotaFiscalEletronicaConsultaDTO } from './models/NotaFiscalEletronicaConsultaDTO';
export type { Obrigatoriedade } from './models/Obrigatoriedade';
export type { OrgaoConsultaDTO } from './models/OrgaoConsultaDTO';
export type { OrgaoEntidade } from './models/OrgaoEntidade';
export type { OrgaoEntidadeDTO } from './models/OrgaoEntidadeDTO';
export type { PaginaRetornoAtaRegistroPrecoDTO } from './models/PaginaRetornoAtaRegistroPrecoDTO';
export type { PaginaRetornoRecuperarContratoDTO } from './models/PaginaRetornoRecuperarContratoDTO';
export type { PaisResumidoDTO } from './models/PaisResumidoDTO';
export type { PlanoContratacaoComItensDTO } from './models/PlanoContratacaoComItensDTO';
export type { PlanoContratacaoItemOrgaoToDTO } from './models/PlanoContratacaoItemOrgaoToDTO';
export type { PlanoContratacaoOrgaoDTO } from './models/PlanoContratacaoOrgaoDTO';
export type { PlanoSequencialConsolidadoDTO } from './models/PlanoSequencialConsolidadoDTO';
export type { RecuperarAtaRegistroPrecoDTO } from './models/RecuperarAtaRegistroPrecoDTO';
export type { RecuperarCompraItemResultadoDTO } from './models/RecuperarCompraItemResultadoDTO';
export type { RecuperarCompraItemSigiloDTO } from './models/RecuperarCompraItemSigiloDTO';
export type { RecuperarContratoDTO } from './models/RecuperarContratoDTO';
export type { RecuperarDadosDocumentoAtaDTO } from './models/RecuperarDadosDocumentoAtaDTO';
export type { RecuperarDadosDocumentoCompraDTO } from './models/RecuperarDadosDocumentoCompraDTO';
export type { RecuperarDadosDocumentoContratoDTO } from './models/RecuperarDadosDocumentoContratoDTO';
export type { RecuperarDadosDocumentoTermoContratoDTO } from './models/RecuperarDadosDocumentoTermoContratoDTO';
export type { RecuperarFornecedorDTO } from './models/RecuperarFornecedorDTO';
export type { RecuperarHistoricoAtaDTO } from './models/RecuperarHistoricoAtaDTO';
export type { RecuperarHistoricoCompraDTO } from './models/RecuperarHistoricoCompraDTO';
export type { RecuperarHistoricoContratoDTO } from './models/RecuperarHistoricoContratoDTO';
export type { RecuperarImagemContratacaoItemDTO } from './models/RecuperarImagemContratacaoItemDTO';
export type { RecuperarOrgaoEntidadeDTO } from './models/RecuperarOrgaoEntidadeDTO';
export type { RecuperarTermoContratoDTO } from './models/RecuperarTermoContratoDTO';
export type { RecuperarUnidadeOrgaoDTO } from './models/RecuperarUnidadeOrgaoDTO';
export type { RecuperarValoresCategoriaItemPcaDTO } from './models/RecuperarValoresCategoriaItemPcaDTO';
export type { RespostaErroValidacaoDTO } from './models/RespostaErroValidacaoDTO';
export type { RetificarInstrumentoCobrancaContratoDTO } from './models/RetificarInstrumentoCobrancaContratoDTO';
export type { RetificarParcialPlanoContratacaoItemDTO } from './models/RetificarParcialPlanoContratacaoItemDTO';
export type { RetificarParcialPlanoContratacaoListaItensDTO } from './models/RetificarParcialPlanoContratacaoListaItensDTO';
export type { SequenciaisDTO } from './models/SequenciaisDTO';
export type { TipoAmparoLegal } from './models/TipoAmparoLegal';
export type { TipoContrato } from './models/TipoContrato';
export type { TipoInstrumentoCobrancaDTO } from './models/TipoInstrumentoCobrancaDTO';
export type { TipoInstrumentoConvocatorio } from './models/TipoInstrumentoConvocatorio';
export type { TipoInstrumentoConvocatorioDTO } from './models/TipoInstrumentoConvocatorioDTO';
export type { TipoInstrumentoConvocatorioModoDisputaDTO } from './models/TipoInstrumentoConvocatorioModoDisputaDTO';
export type { TipoMargemPreferenciaDTO } from './models/TipoMargemPreferenciaDTO';
export type { UF } from './models/UF';
export type { UnidadeOrgao } from './models/UnidadeOrgao';
export type { UnidadeOrgaoDTO } from './models/UnidadeOrgaoDTO';

export { AmparoLegalService } from './services/AmparoLegalService';
export { AtaService } from './services/AtaService';
export { CategoriaDeItemService } from './services/CategoriaDeItemService';
export { CatLogoService } from './services/CatLogoService';
export { ConformidadeInstrumentoConvocatRioEModoDeDisputaService } from './services/ConformidadeInstrumentoConvocatRioEModoDeDisputaService';
export { ConformidadeInstrumentoConvocatRioModalidadeDeContrataOEAmparoLegalService } from './services/ConformidadeInstrumentoConvocatRioModalidadeDeContrataOEAmparoLegalService';
export { ConformidadeModalidadeECritRioDeJulgamentoService } from './services/ConformidadeModalidadeECritRioDeJulgamentoService';
export { ConformidadeModalidadeEFonteOrAmentariaService } from './services/ConformidadeModalidadeEFonteOrAmentariaService';
export { ContrataOService } from './services/ContrataOService';
export { ContratoEmpenhoService } from './services/ContratoEmpenhoService';
export { CritRioDeJulgamentoService } from './services/CritRioDeJulgamentoService';
export { FonteOrAmentRiaService } from './services/FonteOrAmentRiaService';
export { FonteOrAmentRiaDaContrataOService } from './services/FonteOrAmentRiaDaContrataOService';
export { InstrumentoConvocatRioService } from './services/InstrumentoConvocatRioService';
export { InstrumentoDeCobranADeContratoEmpenhoService } from './services/InstrumentoDeCobranADeContratoEmpenhoService';
export { ModalidadeService } from './services/ModalidadeService';
export { ModoDeDisputaService } from './services/ModoDeDisputaService';
export { PlanoDeContrataOService } from './services/PlanoDeContrataOService';
export { RgOService } from './services/RgOService';
export { TermoDeContratoService } from './services/TermoDeContratoService';
export { TipoDeInstrumentoDeCobranAService } from './services/TipoDeInstrumentoDeCobranAService';
export { UnidadeService } from './services/UnidadeService';
export { UsuRioService } from './services/UsuRioService';
