/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { ResponseFormat } from './ResponseFormat';
export type VlmModelApi = {
  /**
   * Endpoint which accepts openai-api compatible requests.
   */
  url: string;
  /**
   * Headers used for calling the API endpoint. For example, it could include authentication headers.
   */
  headers?: Record<string, string>;
  /**
   * Model parameters.
   */
  params?: Record<string, any>;
  /**
   * Timeout for the API request.
   */
  timeout?: number;
  /**
   * Maximum number of concurrent requests to the API.
   */
  concurrency?: number;
  /**
   * Prompt used when calling the vision-language model.
   */
  prompt?: string;
  /**
   * Scale factor of the images used.
   */
  scale?: number;
  /**
   * Type of response generated by the model.
   */
  response_format: ResponseFormat;
  /**
   * Temperature parameter controlling the reproducibility of the result.
   */
  temperature?: number;
};

