/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { InferenceFramework } from './InferenceFramework';
import type { ResponseFormat } from './ResponseFormat';
import type { TransformersModelType } from './TransformersModelType';
export type VlmModelLocal = {
  /**
   * Repository id from the Hugging Face Hub.
   */
  repo_id: string;
  /**
   * Prompt used when calling the vision-language model.
   */
  prompt?: string;
  /**
   * Scale factor of the images used.
   */
  scale?: number;
  /**
   * Type of response generated by the model.
   */
  response_format: ResponseFormat;
  /**
   * Inference framework to use.
   */
  inference_framework: InferenceFramework;
  /**
   * Type of transformers auto-model to use.
   */
  transformers_model_type?: TransformersModelType;
  /**
   * Config from https://huggingface.co/docs/transformers/en/main_classes/text_generation#transformers.GenerationConfig
   */
  extra_generation_config?: Record<string, any>;
  /**
   * Temperature parameter controlling the reproducibility of the result.
   */
  temperature?: number;
};

