import * as ts from 'typescript';
import * as path from 'path';
import * as fs from 'fs';

/**
 * Intelligent Schema Resolver
 * Resolves complex TS utility types (Omit, Parameters, etc.) into TypeBox schemas.
 */

function generateSchemas(filePath: string) {
    const absolutePath = path.resolve(filePath);

    // 1. Create Program
    const program = ts.createProgram([absolutePath], {
        target: ts.ScriptTarget.ESNext,
        module: ts.ModuleKind.CommonJS,
        baseUrl: '.',
        paths: {
            '@/*': ['./src/*']
        }
    });

    const checker = program.getTypeChecker();
    const sourceFile = program.getSourceFile(absolutePath);

    if (!sourceFile) {
        console.error(`Could not find source file: ${filePath}`);
        return;
    }

    // 2. Find the Controller namespace
    let controllerNamespace: ts.ModuleDeclaration | undefined;
    ts.forEachChild(sourceFile, node => {
        if (ts.isModuleDeclaration(node) && node.name.text.endsWith('Controller')) {
            controllerNamespace = node;
        }
    });

    if (!controllerNamespace) {
        console.error(`Could not find Controller namespace in ${filePath}`);
        return;
    }

    console.log(`Found namespace: ${controllerNamespace.name.text}`);

    const results: Record<string, string> = {};

    // 3. Resolve exported types in the namespace
    if (controllerNamespace.body && ts.isModuleBlock(controllerNamespace.body)) {
        controllerNamespace.body.statements.forEach(statement => {
            if (ts.isTypeAliasDeclaration(statement) || ts.isInterfaceDeclaration(statement)) {
                const typeName = statement.name.text;
                if (['Headers', 'Body', 'Query', 'Params', 'Response'].includes(typeName)) {
                    const type = checker.getTypeAtLocation(statement.name);
                    results[typeName] = resolveTypeToTypeBox(type, checker, statement.name);
                }
            }
        });
    }

    // 4. Generate Output
    const controllerName = controllerNamespace.name.text;
    const defaultSuccessCode = controllerName.startsWith('Create') ? 201 : 200;

    // Define unique IDs for the schemas based on controller name
    const bodyId = `${controllerName}Body`;
    const responseId = `${controllerName}Response`;
    const paramsId = `${controllerName}Params`;
    const queryId = `${controllerName}Query`;
    const headersId = `${controllerName}Headers`;

    const output = `// @generated by Intelligent Resolver
import { Type, Static } from "@sinclair/typebox";

export namespace ${controllerName} {
${Object.entries(results).map(([name, schema]) => {
        let idString = '';
        if (name === 'Body') idString = `, { $id: '${bodyId}' }`;
        if (name === 'Response') idString = `, { $id: '${responseId}' }`;
        if (name === 'Params') idString = `, { $id: '${paramsId}' }`;
        if (name === 'Query') idString = `, { $id: '${queryId}' }`;
        if (name === 'Headers') idString = `, { $id: '${headersId}' }`;

        // Inject ID into the Type.Object/Type.xxx call if it's top level
        // Simplistic injection: replace the closing ')' with ', { $id: ... })' 
        // BUT this assumes the schema string ends with ')'. 
        // Better: Explicitly wrapping or appending options. 
        // Given resolveTypeToTypeBox structure, it usually returns 'Type.Object({...})' or 'Type.String()'
        // We can check if it ends with '})' or just ')'

        // However, TypeBox options are the last argument. 
        // Let's rely on a helper or string manipulation for now OR
        // modifying the resolved string to inject options is tricky without parsing.

        // Alternative: Wrap it? Type.Unsafe(...) no.

        // Let's modify resolveTypeToTypeBox or just append the options if it looks safe.
        // Actually, for Type.Object(...), we can splice it.

        let schemaWithId = schema;
        if (idString) {
            if (schema.endsWith('()')) {
                const cleanOptions = idString.replace(/^, /, '');
                schemaWithId = schema.slice(0, -1) + cleanOptions + ')';
            } else if (schema.endsWith(')')) {
                schemaWithId = schema.slice(0, -1) + idString + ')';
            }
        }

        return `  export const ${name} = ${schemaWithId};\n  export type ${name} = Static<typeof ${name}>;`;
    }).join('\n\n')}
}

/**
 * Helper to generate Fastify schema for this controller
 */
export const make${controllerName.replace('Controller', '')}Schema = (successCode = ${defaultSuccessCode}) => {
  const schema: any = {};

  // Check if Body is defined and NOT null type (even if it has other options like $id)
  if (${controllerName}.Headers && (typeof ${controllerName}.Headers !== 'undefined') && ((${controllerName}.Headers as any).type !== 'null')) {
    schema.headers = { $ref: '${headersId}#' };
  }

  if (${controllerName}.Body && (typeof ${controllerName}.Body !== 'undefined') && ((${controllerName}.Body as any).type !== 'null')) {
    schema.body = { $ref: '${bodyId}#' };
  }

  if (${controllerName}.Query && (typeof ${controllerName}.Query !== 'undefined') && ((${controllerName}.Query as any).type !== 'null')) {
    schema.querystring = { $ref: '${queryId}#' };
  }

  if (${controllerName}.Params && (typeof ${controllerName}.Params !== 'undefined') && ((${controllerName}.Params as any).type !== 'null')) {
    schema.params = { $ref: '${paramsId}#' };
  }

  if (${controllerName}.Response && (typeof ${controllerName}.Response !== 'undefined') && ((${controllerName}.Response as any).type !== 'null')) {
    schema.response = {
      [successCode]: { $ref: '${responseId}#' }
    };
  }

  return schema;
};
`;

    const outputPath = filePath.replace('.ts', 'Schemas.ts');
    const absoluteOutputPath = path.resolve(outputPath);
    fs.writeFileSync(absoluteOutputPath, output);
    console.log(`✅ Generated: ${absoluteOutputPath}`);
}

function resolveTypeToTypeBox(type: ts.Type, checker: ts.TypeChecker, location: ts.Node, depth = 0, isHeader = false): string {
    const indent = '  '.repeat(depth + 1);
    const nextIndent = '  '.repeat(depth + 2);

    if (depth > 6) return 'Type.Any()'; // Safety limit

    const typeString = checker.typeToString(type);

    // 1. Detect Built-ins
    if (typeString === 'Date') return 'Type.String({ format: "date-time" })';
    if (typeString === 'Buffer') return 'Type.Uint8Array()';

    // 2. Primitive types
    const flags = type.getFlags();
    if (flags & ts.TypeFlags.String) return 'Type.String()';
    if (flags & ts.TypeFlags.Number) return 'Type.Number()';
    if (flags & ts.TypeFlags.Boolean) return 'Type.Boolean()';
    if (flags & ts.TypeFlags.Undefined || flags & ts.TypeFlags.Void) return 'Type.Null()';
    if (flags & ts.TypeFlags.Null) return 'Type.Null()';

    // 3. String/Number Literal types
    if (type.isStringLiteral()) return `Type.Literal("${type.value}")`;
    if (type.isNumberLiteral()) return `Type.Literal(${type.value})`;

    // 4. Array types
    if (checker.isArrayType(type)) {
        const typeRef = type as ts.TypeReference;
        const elementType = typeRef.typeArguments?.[0] || (type as any).elementType;
        if (elementType) {
            return `Type.Array(${resolveTypeToTypeBox(elementType, checker, location, depth + 1, isHeader)})`;
        }
        return 'Type.Array(Type.Any())';
    }

    // 5. Union types
    if (type.isUnion()) {
        const uniqueTypes = type.types.map(t => resolveTypeToTypeBox(t, checker, location, depth + 1, isHeader));
        const filtered = Array.from(new Set(uniqueTypes)); // Deduplicate
        if (filtered.length === 1) return filtered[0];
        return `Type.Union([\n${filtered.map(t => `${nextIndent}${t}`).join(',\n')}\n${indent}])`;
    }

    // 6. Intersection types
    if (type.isIntersection()) {
        const uniqueTypes = type.types.map(t => resolveTypeToTypeBox(t, checker, location, depth + 1, isHeader));
        const filtered = Array.from(new Set(uniqueTypes)); // Deduplicate
        if (filtered.length === 1) return filtered[0];
        return `Type.Intersect([\n${filtered.map(t => `${nextIndent}${t}`).join(',\n')}\n${indent}])`;
    }

    // 3. Handle Undefined/Void (Map to Null for JSON Schema compatibility)
    if (type.getFlags() & ts.TypeFlags.Undefined || type.getFlags() & ts.TypeFlags.Void) {
        return 'Type.Null()';
    }

    // 4. Handle Objects/Interfaces
    if (type.isClassOrInterface() || type.getFlags() & ts.TypeFlags.Object) {
        // Skip functions/methods
        if (type.getCallSignatures().length > 0) return 'Type.Any()';

        const properties = checker.getPropertiesOfType(type);
        if (properties.length === 0) {
            if (typeString === '{}') return 'Type.Object({})';
            return 'Type.Any()';
        }

        const props = properties
            .filter(prop => {
                const name = prop.getName();
                if (name.startsWith('__')) return false;

                // Exclude authorization from Documentation/Schemas to avoid 
                // it being added as a method parameter in the generated frontend client.
                if (name.toLowerCase() === 'authorization' && isHeader) return false;

                const propType = checker.getTypeOfSymbolAtLocation(prop, location);
                if (!propType) return true;

                // Skip methods
                return propType.getCallSignatures().length === 0;
            })
            .map(prop => {
                const name = prop.getName();
                const propType = checker.getTypeOfSymbolAtLocation(prop, location);
                if (!propType) return `${name}: Type.Any()`;

                let schema = resolveTypeToTypeBox(propType, checker, location, depth + 1, isHeader);

                // Handle optional
                const isOptional = (prop.getFlags() & ts.SymbolFlags.Optional) !== 0;
                if (isOptional) {
                    schema = `Type.Optional(${schema})`;
                }

                return `"${name}": ${schema}`;
            });

        if (props.length === 0) return 'Type.Object({})';

        return `Type.Object({\n${props.map(p => `${nextIndent}${p}`).join(',\n')}\n${indent}})`;
    }

    return 'Type.Any()';
}

// Simple CLI
const args = process.argv.slice(2);
const fileArg = args.indexOf('--file');
if (fileArg !== -1 && args[fileArg + 1]) {
    generateSchemas(args[fileArg + 1]);
} else {
    console.log('Usage: npx ts-node scripts/generate-resolved-schemas.ts --file <path>');
}
