#!/bin/bash
# scripts/generate-schemas.sh

echo "🚀 Generating TypeBox schemas from Controllers..."

# Ensure we are in the back-end directory
cd "$(dirname "$0")/.."

# Find all Controller files, excluding factories (make*)
find src/domain/use-cases -name "*Controller.ts" | while read controller; do
  if [[ "$(basename "$controller")" == make* ]]; then
    continue
  fi
  
  schema="${controller/Controller.ts/ControllerSchemas.ts}"
  
  echo "  ✓ Processing: $(basename "$controller")"
  
  # Generate schema
  # --skip-type-creation: keeps original types and only generates TypeBox code
  npx ts2typebox \
    --input "$controller" \
    --output "$schema" \
    --skip-type-creation > /dev/null 2>&1

  # Add @generated header if the file was created
  if [ -f "$schema" ]; then
    echo -e "// @generated by ts2typebox\n$(cat "$schema")" > "$schema"
  fi
done

echo ""
echo "✅ Done! Generated schemas for all correctly patterned controllers."
echo "📚 Next: Update routes to use these schemas."
