import { z } from "zod";

export const CompanySecondaryCnaeSchema = z.object({
    codigo: z.number().describe("Código CNAE secundário"),
    descricao: z.string().describe("Descrição do CNAE secundário"),
});

export const CompanyProfileSchema = z.object({
    id: z.string().describe("ID da empresa"),
    cnpj: z.string().describe("CNPJ da empresa"),
    razao_social: z.string().describe("Razão social da empresa"),
    nome_fantasia: z.string().nullable().describe("Nome fantasia da empresa"),
    situacao_cadastral: z.string().nullable().describe("Situação cadastral da empresa"),
    data_situacao_cadastral: z.string().nullable().describe("Data da situação cadastral"),
    data_abertura: z.string().nullable().describe("Data de abertura da empresa"),
    porte: z.string().nullable().describe("Porte da empresa"),
    natureza_juridica: z.string().nullable().describe("Natureza jurídica da empresa"),
    cnae_fiscal: z.number().nullable().describe("Código CNAE principal"),
    cnae_fiscal_descricao: z.string().nullable().describe("Descrição do CNAE principal"),
    cnaes_secundarios: z.array(CompanySecondaryCnaeSchema).nullable().describe("Lista de CNAEs secundários"),
    logradouro: z.string().nullable().describe("Logradouro da empresa"),
    numero: z.string().nullable().describe("Número do endereço"),
    complemento: z.string().nullable().describe("Complemento do endereço"),
    bairro: z.string().nullable().describe("Bairro"),
    municipio: z.string().nullable().describe("Município"),
    uf: z.string().nullable().describe("UF da empresa"),
    cep: z.string().nullable().describe("CEP da empresa"),
    telefone_1: z.string().nullable().describe("Telefone principal"),
    email_empresa: z.string().nullable().describe("E-mail da empresa"),
    capital_social: z.number().nullable().describe("Capital social em reais"),
    opcao_pelo_simples: z.boolean().nullable().describe("Indica se a empresa opta pelo Simples"),
    opcao_pelo_mei: z.boolean().nullable().describe("Indica se a empresa opta pelo MEI"),
    organizationId: z.string().describe("ID da organização dona da empresa"),
    createdAt: z.date().describe("Data de criação do registro"),
    updatedAt: z.date().describe("Data da última atualização"),
});

export const CompanyWritableFieldsSchema = z.object({
    cnpj: z.string().describe("CNPJ da empresa"),
    razao_social: z.string().describe("Razão social da empresa"),
    nome_fantasia: z.string().nullable().optional().describe("Nome fantasia da empresa"),
    situacao_cadastral: z.string().nullable().optional().describe("Situação cadastral da empresa"),
    data_situacao_cadastral: z.string().nullable().optional().describe("Data da situação cadastral"),
    data_abertura: z.string().nullable().optional().describe("Data de abertura da empresa"),
    porte: z.string().nullable().optional().describe("Porte da empresa"),
    natureza_juridica: z.string().nullable().optional().describe("Natureza jurídica da empresa"),
    cnae_fiscal: z.number().nullable().optional().describe("Código CNAE principal"),
    cnae_fiscal_descricao: z.string().nullable().optional().describe("Descrição do CNAE principal"),
    cnaes_secundarios: z.array(CompanySecondaryCnaeSchema).nullable().optional().describe("Lista de CNAEs secundários"),
    logradouro: z.string().nullable().optional().describe("Logradouro da empresa"),
    numero: z.string().nullable().optional().describe("Número do endereço"),
    complemento: z.string().nullable().optional().describe("Complemento do endereço"),
    bairro: z.string().nullable().optional().describe("Bairro"),
    municipio: z.string().nullable().optional().describe("Município"),
    uf: z.string().nullable().optional().describe("UF da empresa"),
    cep: z.string().nullable().optional().describe("CEP da empresa"),
    telefone_1: z.string().nullable().optional().describe("Telefone principal"),
    email_empresa: z.string().nullable().optional().describe("E-mail da empresa"),
    capital_social: z.number().nullable().optional().describe("Capital social em reais"),
    opcao_pelo_simples: z.boolean().nullable().optional().describe("Indica se a empresa opta pelo Simples"),
    opcao_pelo_mei: z.boolean().nullable().optional().describe("Indica se a empresa opta pelo MEI"),
});
